### ISSUE TITLE
can`t fetch stats

### ISSUE THREAD

**Issue by dnj0104** [retroflex/MMM-Overwatch#1]
Hello

I'm trying to fetch data from ow-api but I'm failing.

platform: psn and correct battletag, have talked with ow-api creator
and he was given me this 
`
https://ow-api.com/v1/stats/platform/battletag/profile `(witch work fine when input in browser)

So my question is how do I make that link usable in mmm-overwatch-module.

when I type my platform and battletag in module in config array I just get 
`MMM-Overwatch error when fetching data: StatusCodeError: 404 - "404 page not found\n"
`

**Comment by retroflex** [comment]
@dnj0104 Sorry for late answer, haven't seen your message until now. Firstly, I changed the default configuration as those battle tags didn't exist/work anymore. But that should not be your problem I guess.

Secondly, you have to replace # with a - in your battle tag if you haven't done that already. Would you mind sharing your URL?
